/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-System-Beep.h
 #	source generated by 4D Plugin Wizard
 #	Project : System Beep
 #	author : miyako
 #	2022/03/10
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SYSTEM_BEEP_H
#define PLUGIN_SYSTEM_BEEP_H

#include "4DPluginAPI.h"

#pragma mark -

static void SYSTEM_BEEP(PA_PluginParameters params);

namespace beep {

typedef enum {
    
    //windows

    OK = 0,
    ICONASTERISK = 1,
    ICONEXCLAMATION = 2,
    ICONERROR = 3,
    ICONHAND = 4,
    ICONINFORMATION = 5,
    ICONQUESTION = 6,
    ICONSTOP = 7,
    ICONWARNING = 8,
    SYSTEM = 9,
    
    //macOS
    
    Basso = 11,
    Blow = 12,
    Bottle = 13,
    Frog = 14,
    Funk = 15,
    Glass = 16,
    Hero = 17,
    Morsei = 18,
    Ping = 19,
    Pop = 20,
    Purr = 21,
    Sosumi = 22,
    Submarine = 23,
    Tink = 24
    
} beep_type_t;

}

#if VERSIONMAC
#import <AppKit/AppKit.h>
#endif

#if VERSIONWIN
#include "Windows.h"
#endif

#endif /* PLUGIN_SYSTEM_BEEP_H */
