/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-System-Beep.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : System Beep
 #	author : miyako
 #	2022/03/10
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-System-Beep.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- System Beep
            
			case 1 :
				SYSTEM_BEEP(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

static void SYSTEM_BEEP(PA_PluginParameters params) {

    beep::beep_type_t type = (beep::beep_type_t)PA_GetLongParameter(params, 1);
    
    switch (type) {
            
#if VERSIONWIN
        case beep::SYSTEM:
            MessageBeep(0xFFFFFFFF);
            break;

        case beep::OK:
            MessageBeep(MB_OK);
            break;

        case beep::ICONASTERISK:
            MessageBeep(MB_ICONASTERISK);
            break;

        case beep::ICONEXCLAMATION:
            MessageBeep(MB_ICONEXCLAMATION);
            break;

        case beep::ICONERROR:
            MessageBeep(MB_ICONERROR);
            break;

        case beep::ICONHAND:
            MessageBeep(MB_ICONHAND);
            break;

        case beep::ICONINFORMATION:
            MessageBeep(MB_ICONINFORMATION);
            break;

        case beep::ICONQUESTION:
            MessageBeep(MB_ICONQUESTION);
            break;
            
        case beep::ICONSTOP:
            MessageBeep(MB_ICONSTOP);
            break;
            
        case beep::ICONWARNING:
            MessageBeep(MB_ICONWARNING);
            break;
            
#endif
            
#if VERSIONMAC
        case beep::SYSTEM:
            NSBeep();
            break;
            
        case beep::Basso:
            [[NSSound soundNamed:@"Basso"]play];
            break;

        case beep::Blow:
            [[NSSound soundNamed:@"Blow"]play];
            break;

        case beep::Bottle:
            [[NSSound soundNamed:@"Bottle"]play];
            break;
            
        case beep::Frog:
            [[NSSound soundNamed:@"Frog"]play];
            break;
            
        case beep::Funk:
            [[NSSound soundNamed:@"Funk"]play];
            break;
            
        case beep::Glass:
            [[NSSound soundNamed:@"Glass"]play];
            break;
            
        case beep::Hero:
            [[NSSound soundNamed:@"Hero"]play];
            break;
            
        case beep::Morsei:
            [[NSSound soundNamed:@"Morsei"]play];
            break;
            
        case beep::Ping:
            [[NSSound soundNamed:@"Ping"]play];
            break;
            
        case beep::Pop:
            [[NSSound soundNamed:@"Pop"]play];
            break;
            
        case beep::Purr:
            [[NSSound soundNamed:@"Purr"]play];
            break;
            
        case beep::Sosumi:
            [[NSSound soundNamed:@"Sosumi"]play];
            break;
            
        case beep::Submarine:
            [[NSSound soundNamed:@"Submarine"]play];
            break;
            
        case beep::Tink:
            [[NSSound soundNamed:@"Tink"]play];
            break;
            
#endif
        default:
            break;
    }
    
    
}

